[package]
name = "unemployment"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
ruff_python_ast = { git = "https://github.com/astral-sh/ruff", tag = "0.12.10" }
ruff_python_parser = { git = "https://github.com/astral-sh/ruff", tag = "0.12.10" }
